### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by aadamsx** [selfup/nextjs-docker#5]
I don't see any process manager here like PM2, so what if Next crashes?

I don't the --production flag on npm install

Also, no nginx proxy

Also for hot-reloading to work with Next and Docker you'll need to add this to the config

```javascript
webpackDevMiddleware: config => {
  config.watchOptions = {
    poll: 1000,
    aggregateTimeout: 300,
  }
  return config
}
```

And add volumes to the docker-compose.

**Comment by selfup** [comment]
I am honestly surprised this got so much traction. If next crashes I would hope you have more than one container available. If we start assuming people are using nginx/etc.. we create a lot of scope creep and pre-dictate their infrastructure. Some run docker-compose in prod, some have full control of their k8s environment. Some deploy to more PaaS like infra and the ingress/etc.. is all handled for them. 

This is more of a template/starting ground for being ready to go to prod. I'll change the README so we can avoid further confusion. `npm install` should read the exposed `ENV` set here https://github.com/selfup/nextjs-docker/blob/master/Dockerfile#L7

If that is no longer the case I can add `--production`.

I mainly made this so that people could have small/non-root images for building/deploying their working nextjs apps.

To add: not everyone develops inside of their running containers. Most rely on local dev, a build process, deploy to lower envs, go through acceptance testing, etc..

Another reason I did not include it is because it would add additional scope creep.
